version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  gateway-service:
    build: ./gateway-service
    image: gateway_service_img
    ports:
      - 8083:8083
    environment:
      - PORT=8083
    depends_on:
      - db
  user-service:
    build: ./user-service
    image: user_service_img
    ports:
      - 8888:8888
    environment:
      - PORT=8888
    depends_on:
      - db
  matching-service:
    build: ./matching-service
    image: matching_service_img
    ports:
      - 8889:8889
    environment:
      - PORT=8889
    depends_on:
      - db
  chat-service:
    build: ./chat-service
    image: chat_service_img
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    depends_on:
      - db
volumes:
  db:
    driver: local
